name = str(input("What is your name? "))
action = input("Ok. Now enter an action: ")
print()
print("I'm sorry, " + name + ". I'm afraid I can't do that.")
print("(The action \"" + action + "\" was not performed.)")